name: 'tekartik_mdl_js_react'
version: 0.3.0
description: Material design lite base resources and wrappers
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  react: any
  tekartik_mdl_js:
    git: git://github.com/alextekartik/mdl_js.dart
dev_dependencies:
  test: any
dependency_overrides:
  tekartik_mdl_js:
    path: ../mdl_js.dart
